name: "Jaswinder Singh"
description: "Student, Web buff, Critical Thinking, Music Lover, DIY, Life Hacking, Fortune 500, and 8."

email: "&#106;&#97;&#115;&#119;&#105;&#110;&#100;&#101;&#114;&#64;&#119;&#105;&#115;&#101;&#108;&#111;&#111;&#107;&#46;&#99;&#111;&#46;&#105;&#110;"
simple_email: "s.jaswinder03@gmail.com"
phone: "+91 91-7076-3758"
phone_noFormat: "+919170763758"
address: "Lakhimpur Kheri, Uttar Pradesh, IN"
DOB: "October 26, 1996" 

twitter_username: "@itsjaswinder"

facebook: "http://facebook.com/jassithedude"
twitter: "http://twitter.com/itsjaswinder"
instagram: "http://instagram.com/damnslow"
github: "http://github.com/jaswinder-singh"
youtube: "https://www.youtube.com/channel/UCporjZoVfoouw_myBh4jAaA"
googleplus: "https://plus.google.com/+JaswinderSingh26"
linkedin: "https://in.linkedin.com/in/itsjaswinder"

url: "http://jaswinder-singh.github.io"
pretty_url: "jaswinder-singh.github.io"

# paginate: 10

markdown: kramdown
permalink: /post/:title.html