name: "Jaswinder Singh"
description: "Internet, Gadgets, DIY, Tech Savvy, Life Hacking, Fortune 500, and 8."

url: "http://jaswinder-singh.github.io"
# url: "http://localhost:4000"
# url: "http://192.168.0.101:4000"

# paginate: 10

markdown: rdiscount
permalink: /post/:title.html
# pygments: true
